#== Prison 2.0 Configuration ==#
#     (C) 2014 SirFaizdat      #
#== == == == === == == == == ==#

server-prefix: "&4Prison &7>"
check-updates: true

# == MINES == #

fetch-online-item-list: true
reset-time: 10
reset-warnings: [10,5,1]
fill-mode: true

reset-warning-message: "&6Mines will reset in &c<mins> &6minutes!"
reset-broadcast-message: "&2Mines have been reset!"

# == RANKS == #

# Ranks now supports multi-world support.
# For example, if you want players to be ranked up in only
# the worlds "plots" and "mines", specify them in the list below. If you
# want to enable this, change multiworld to true. If you want them to 
# rank up in all worlds, just leave it at false.
# It is highly recommended that you read the guide on the Bukkit page.
# ===== THIS FEATURE IS FOR ADVANCED USERS ONLY! ===== #

multiworld: false
world-list: [plots, mines]