#== Prison 2.0 Configuration ==#
#     (C) 2014 SirFaizdat      #
#== == == == === == == == == ==#

server-prefix: "&4Prison &7>"
check-updates: true

# == MINES == #

reset-time: 10
reset-warnings: [10,5,1]
fill-mode: true

reset-warning-message: "&6Mines will reset in &c<mins> &6minutes!"
reset-broadcast-message: "&2Mines have been reset!"

# == SCOREBOARDS == #

enable-scoreboards: true
scoreboard-name: "&6&lPrison"
update-interval: 1
